version: '3'

services:
        wordpress:
                image: wordpress:latest
                ports:
                        - "8000:80"
                restart: always
                environment:
                        WORDPRESS_DB_USER: wordpress
                        WORDPRESS_DB_PASSWORD: wordpress
                        WORDPRESS_DB_NAME: wordpress

        mariadb:
                build: requirements/mariadb/
                container_name: mariadb
                ports:
                        - "3306:3306"
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: password
                        MYSQL_DATABASE: wordpress
                volumes:
                - "~/Document/docker/mariadb:/var/lib/mysql"


volumes:
        wp_database: {}
        wp_files: {}

