version: '3.5'

services:
        nginx:
                container_name: nginx
                ports:
                        - "80:80"
                        - "443:443"
                build:
                        context: requirements/nginx
                        dockerfile: Dockerfile
                depends_on:
                        - wordpress
                networks:
                        - inception
                volumes:
                        - wp:/var/www/
                restart: always
        wordpress:
                container_name: wordpress
                depends_on:
                        - mariadb
                build:
                        context: requirements/wordpress
                        dockerfile: Dockerfile
                        args:
                                DB_NAME: $${DB_ROOT}
                                DB_USER: $${DB_USER}
                                DB_PASS: $${DB_PASS}
                                DB_ROOT: $${DB_ROOT}
                restart: always
                volumes:
                  - wp:/var/www/html
                env_file: .env
                networks:
                  - inception

        mariadb:
                container_name: mariadb
                build:
                        context: requirements/mariadb
                        dockerfile: Dockerfile
                volumes:
                  - db:/var/lib/mariadb
                restart: always
                networks:
                  - inception
                env_file: .env

volumes:
        db: 
                driver: local
                name: db 
                driver_opts:
                        type: none
                        o: bind
                        device: /home/adesgran/data/mariadb
        wp: 
                driver: local
                name: wp
                driver_opts:
                        type: none
                        o: bind
                        device: /home/adesgran/data/wordpress

networks:
        inception:
                driver: bridge
