version: '3.5'

services:
        wordpress:
                container_name: wordpress
                depends_on:
                        - mariadb
                build:
                        context: requirements/wordpress
                        dockerfile: Dockerfile
                        args:
                                DB_NAME: mariadb
                                DB_USER: ${DB_USER}
                                DB_PASS: ${DB_PASS}
                                DB_ROOT: ${DB_ROOT}
                ports:
                        - "80:80"
                restart: always
                volumes:
                  - wp:/var/www/html
                env_file: .env
                networks:
                  - inception

        mariadb:
                image: mariadb:latest
                container_name: mariadb
                ports:
                        - "3306:3306"
                environment:
                        MYSQL_ROOT_PASSWORD: ${DB_ROOT}
                        MYSQL_DATABASE: ${DB_NAME}
                        MYSQL_USER: ${DB_USER}
                        MYSQL_PASSWORD: ${DB_PASS}
                volumes:
                  - db:/var/lib/mariadb
                restart: always
                networks:
                  - inception
                env_file: .env
#                build: requirements/mariadb/

volumes:
        db: 
                driver: local
                name: db 
                driver_opts:
                        type: none
                        o: bind
                        device: /home/adesgran/data/mariadb
        wp: 
                driver: local
                name: wp
                driver_opts:
                        type: none
                        o: bind
                        device: /home/adesgran/data/wordpress

networks:
        inception:
                driver: bridge
