version: '3.5'

services:
        wordpress:
                container_name: wordpress
                depends_on:
                        - mariadb
                build:
                        context: requirements/wordpress
                        dockerfile: Dockerfile
                        args:
                                DB_NAME: mariadb
                                DB_USER: ${DB_USER}
                                DB_PASS: ${DB_PASS}
                                DB_ROOT: ${DB_ROOT}
                ports:
                        - "80:80"
                restart: always
                volumes:
                  - wp:/var/www/html
                env_file: .env

        mariadb:
                image: mariadb:10.7
                container_name: mariadb
                ports:
                        - "3306:3306"
                volumes:
                  - db:/var/lib/mariadb
                restart: always
                env_file: .env
#                build: requirements/mariadb/

volumes:
        db: {}
        wp: 
                driver: local
                name: wp
                driver_opts:
                        type: none
                        o: bind
                        device: /home/adesgran/data/wordpress

networks:
        incpetion:
                driver: bridge
